# Generated by Django 4.1.3 on 2022-11-15 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_rename_hashtag_category_delete_post_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='hashtags',
            new_name='category',
        ),
    ]
