# Generated by Django 4.1.3 on 2022-11-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_product_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='product',
        ),
    ]
